version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "pre_build"
      - npm install
  pre_build:
    commands:
      - echo "pre_build"
      - npm run build
      - npm run export
      - aws s3 sync build/ s3://test-code-build-wilf
  post_build:
    commands:
      - echo "Finishing up"
